/**
 * The sidebar is autogenerated from the `docs/` directory structure.
 *
 * Ordering is controlled with:
 *  - `sidebar_position` front matter on individual docs
 *  - `_category_.json` files inside category folders
 */
module.exports = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};
