name: Build Projects

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build ${{ matrix.project }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - App
          - AppDraw
          - Network
          - RCCService
          - Base
          - boost.static
          - boost.test
          - GfxBase
          - RbxG3D
          - graphics3D
          - RbxTestHooks
          - Base.UnitTest
          - App.UnitTest
          - App.UnitTest.Run
          - Base.UnitTest.Run
          - Base.UnitTest.Lib
          - RobloxStudio
          - Log
          - WindowsClient
          - App.UnitTest.Lib
          - RobloxTest
          - RobloxTest.Run
          - RobloxTest.PhysicsPerfTest.Run
          - RCCService.PrepForUpload
          - WindowsClient.PrepForUpload
          - RobloxStudio.PrepForUpload
          - PrepAllForUpload
          - RobloxTest.PhysicsTests.Run
          - RobloxTest.MultiPlayerTest.Run
          - GfxCore
          - GfxRender
          - CSG
          - App.BulletPhysics
          - CoreScriptConverter2
          - Microsoft.Xbox.GameChat
          - Microsoft.Xbox.Samples.NetworkMesh
          - XboxClient
          - Bootstrapper
          - BootstrapperClient
          - NPRobloxProxy.PrepForUpload
          - RobloxProxy.PrepForUpload
          - NPRobloxProxy
          - BootstrapperQTStudio
          - BootstrapperQTStudio.PrepForUpload
          - BootstrapperRccService
          - BootstrapperRccService.PrepForUpload
          - RobloxProxy
          - BootstrapperClient.PrepForUpload
          - RobloxModelAnalyzer
          - Roblox.RccServiceArbiter
          - ScriptSigner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Build Project
        run: msbuild Roblox.sln /t:"${{ matrix.project }}" /p:Configuration=Release /p:Platform="Win32"
